spring:
  application:
    name: digital-wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_wallet
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms         # timeout kết nối tới Redis server
      connect-timeout: 2000ms # timeout khi thiết lập kết nối lần đầu


  jpa:
    show-sql: true
    # Cấu hình Hibernate (ORM)
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 25 # Kích hoạt batch fetching (tải theo lô)

jwt:
  secret: ${SECRET_KEY}
  access-token-expiration: 900000 # 15 phút
  refresh-token-expiration: 604800000 # 7 ngày
